source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SideMenu_Example', :exclusive => true do
  pod "SideMenu", :path => "../"
end

target 'SideMenu_Tests', :exclusive => true do
  pod "SideMenu", :path => "../"

  
end
